<?xml version="1.0" encoding="utf-8"?><Database Name="Training" Class="TrainingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Training;Integrated Security=True" SettingsObjectName="ConsoleApp1.My.MySettings" SettingsPropertyName="ConnStr" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Assets">
    <Type Name="Asset">
      <Column Name="pID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pCost" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="pInstock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="creDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="creUser" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="amdDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="amdUser" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>